Feature/project study
dbuksha/lunch-order pull request #12
Opened 2021-08-27 09:25 UTC by dmshpakov

- template for admin panel has been added;
- page with dishes has been added;
- page with adding and editing a dish has been added.

2021-08-27 14:50 UTC, Laconiez requested changes

2021-08-27 14:50 UTC, Laconiez commented on src/router/routes-props.ts
> +    path: '/dashboard',
лучше это назвать /admin а следующие пути - /admin/dishes и т.д.

2021-08-27 14:50 UTC, Laconiez commented on src/pages/Home.tsx
> +      <Button
нет, в админку можно зайти только по url

2021-09-03 15:20 UTC, closed without merging

2021-09-03 15:21 UTC, dmshpakov commented
make other pull request