Добавление пары: гарнир + главное блюдо в общий список заказа.
dbuksha/lunch-order pull request #23
Opened 2021-10-26 09:30 UTC by dmshpakov

Добавил компоновку пары: гарнир + главное блюдо в общем списке заказа. Доработал логику расчета стоимости.

2021-10-26 16:48 UTC, Laconiez requested changes

2021-10-26 16:48 UTC, Laconiez commented on src/pages/OrdersDelivery/useGroupedDishes.ts
> +        ...garnirDontPair,
тут совпало сразу два слова - гарнир у нас side dish или side. Что-то без пары - unmatched или лучше unpaired.

2021-10-26 16:48 UTC, Laconiez commented on src/pages/OrdersDelivery/useGroupedDishes.ts
> +      Object.defineProperty(el, 'quantity', {
результатом map должен быть иммутабельный массив. в смысле нельзя менять входящие значения, нужно из входного параметра сделать копию и работать с ней. или будут интересные и неожиданные ошибки несработавших обновлений рендера

2021-10-26 16:48 UTC, Laconiez commented on src/pages/OrdersDelivery/useGroupedDishes.ts
> +  dishArr.forEach((el, ind) => {
а можешь переделать на filter и find?

2021-10-26 16:48 UTC, Laconiez commented on src/pages/OrdersDelivery/useGroupedDishes.ts
> +  arr.forEach((el) => {
это лучше писать с filter

2021-10-26 16:48 UTC, Laconiez commented on src/pages/OrdersDelivery/useGroupedDishes.ts
> +        dishesWithUser: el.dishes.map((item) => {
может personalisedDishes?

2021-10-26 16:48 UTC, Laconiez commented on src/pages/OrdersDelivery/useGroupedDishes.ts
> +    const dishes = [...mainDishes, ...addDish];
нужно разбить функцию, а то она длинная и делает вообще все сразу

2021-10-27 13:27 UTC, dmshpakov commented on src/pages/OrdersDelivery/useGroupedDishes.ts
> +        ...garnirDontPair,
Поправил

2021-10-27 13:28 UTC, dmshpakov commented on src/pages/OrdersDelivery/useGroupedDishes.ts
> +      Object.defineProperty(el, 'quantity', {
Поправил

2021-10-27 13:28 UTC, dmshpakov commented on src/pages/OrdersDelivery/useGroupedDishes.ts
> +  dishArr.forEach((el, ind) => {
Переделал. Получилось достаточно быстро, сам и не понял почему с самого начало этого не сделал.

2021-10-27 13:29 UTC, dmshpakov commented on src/pages/OrdersDelivery/useGroupedDishes.ts
> +  arr.forEach((el) => {
Переписал с filter

2021-10-27 13:29 UTC, dmshpakov commented on src/pages/OrdersDelivery/useGroupedDishes.ts
> +        dishesWithUser: el.dishes.map((item) => {
Полностью согласен))

2021-10-27 13:30 UTC, dmshpakov commented on src/pages/OrdersDelivery/useGroupedDishes.ts
> +    const dishes = [...mainDishes, ...addDish];
Вынес несколько логических частей в отдельные функции

2021-11-02 07:03 UTC, Laconiez approved these changes

2021-11-02 07:03 UTC, merged