Добавление режима депозита
dbuksha/lunch-order pull request #24
Opened 2021-11-18 13:19 UTC by dmshpakov

Что сделано:
- добавлена страница профиля пользователя, где можно отслеживать актуальный баланс и просматривать историю пополнений счета и заказов;
- добавлена страница пополнения баланса пользователей (в админке);
- добавлен чекбокс с возможностью включения и отключения режима депозитов для пользователей;
- изменена страница заказа доставки: для каждого из режима используется свой компонент.
- исправлено два бага: баг при заказе еды и при заказе еды через админ-панель.

2021-11-18 15:19 UTC, Laconiez requested changes

2021-11-18 15:19 UTC, Laconiez commented on src/utils/time-helper.ts
> +import { Console } from 'console';
кажется это лишний импорт

2021-11-18 15:19 UTC, Laconiez commented on src/utils/orders/calculateDishesPrice.ts
> +export const numberWithSpaces = (x: number): string => {
эту штуку правильнее назвать formatCurrency потому что число с пробелами не особо отражает смысл

2021-11-18 15:19 UTC, Laconiez commented on src/utils/message.ts
>      ordersStr += `${el.person!.name}${
А разве нет типа person в Order? Хорошо бы добавить, чтобы не писать с восклицательными знаками. И переделай пожалуйста forEach на reduce

2021-11-18 15:19 UTC, Laconiez commented on src/components/SiteLayout/SiteHeader.tsx
> +/* eslint-disable no-nested-ternary */
Если выделить в отдельный компонент линк для перехода к профилю - не придется включать это правило. Вложенные тернарники лучше сразу зарефакторить

2021-11-18 15:19 UTC, Laconiez commented on src/components/AdminComponents/Layout/DashboardSidebar.tsx
> +export type Props = {
Если переиспользуешь этот тип - ему нужно какое-то более индентифицирующее название,  HasDepositProps хотя бы. Может придумаешь что-то лучше

2021-11-18 15:19 UTC, Laconiez commented on src/entities/Order.ts
> +  summa?: number;
это должно быть amount или totalCost

2021-11-18 15:19 UTC, Laconiez commented on src/entities/Order.ts
>    person: DocumentReference<DocumentData>;
А здесь разве не User должен быть в качестве типа?

2021-11-18 15:19 UTC, Laconiez commented on src/entities/Transaction.ts
> +  summa: number;
totalCost/amount

2021-11-18 15:19 UTC, Laconiez commented on src/pages/Home.tsx
> +          {currentUser && currentUser.role === 'admin' ? (
currentUser?.role === 'admin' это вроде короче будет

2021-11-18 15:19 UTC, Laconiez commented on src/pages/Home.tsx
> +            {todayOrders && todayOrders.length > 0 ? (
!!todayOrders?.length

2021-11-18 15:19 UTC, Laconiez commented on src/pages/Home.tsx
> +            {todayOrders && todayOrders.length > 0 ? (
там еще выше такие же изменения можно сделать

2021-11-18 15:19 UTC, Laconiez commented on src/pages/Home.tsx
> +              <span className={classes.pinInfo}>{calculatedPrice} руб.</span>
Может использовать не руб. а символ рубля тут?

2021-11-18 15:19 UTC, Laconiez commented on src/store/transactions/transactions-actions.ts
> +    const refillResult = await collectionRefill
у тебя же независимые вызовы коллекций? а что если их вызвать в одном Promise.all? будет в 3 раза быстрее потому что вызовы не будут идти по цепочке

2021-11-18 15:19 UTC, Laconiez commented on src/router/AuthRoute.tsx
> +      await dispatch(fetchSettings());
хороший кейс для Promise.all. независимые коллекции могут выполняться параллельно

2021-11-18 15:19 UTC, Laconiez commented on src/pages/OrdersDelivery/OrdersDeliveryWithoutDeposit.tsx
> +    // await dispatch(fetchUserInfo(currentUser.email!));
это же надо удалить?

2021-11-18 15:19 UTC, Laconiez commented on src/pages/Profile/Profile.tsx
> +import './profile.scss';
может все-таки не тянуть зависимости ради одного использования. условные классы с MUI тоже можно использовать https://stackoverflow.com/questions/58869138/conditionally-rendering-material-ui-styles

2021-11-18 15:19 UTC, Laconiez commented on src/pages/Profile/Profile.tsx
> +                {transactions.some((el) => el.type === 'refill') ? (
по-моему эту часть надо зарефакторить. слишком много условий и кода в разметке компонента

2021-11-18 15:19 UTC, Laconiez commented on src/pages/OrdersDelivery/OrdersDeliveryDeposit.tsx
> +  arr.forEach((el: UserNew) => {
это нужно делать редюсом)

2021-11-18 15:19 UTC, Laconiez commented on package.json
> +    "node-sass": "5.0.0",
можно без sass обойтись я думаю

2021-11-22 17:02 UTC, dmshpakov commented on src/utils/time-helper.ts
> +import { Console } from 'console';
Поправил

2021-11-22 17:02 UTC, dmshpakov commented on src/utils/orders/calculateDishesPrice.ts
> +export const numberWithSpaces = (x: number): string => {
Переименовал

2021-11-22 17:02 UTC, dmshpakov commented on src/utils/message.ts
>      ordersStr += `${el.person!.name}${
Поле person опциональное поле. На reduce переделал.

2021-11-22 17:02 UTC, dmshpakov commented on src/components/SiteLayout/SiteHeader.tsx
> +/* eslint-disable no-nested-ternary */
Переписал: теперь правило не нужно и компонента имеет более читабельный вид.

2021-11-22 17:02 UTC, dmshpakov commented on src/components/AdminComponents/Layout/DashboardSidebar.tsx
> +export type Props = {
Переименовал

2021-11-22 17:02 UTC, dmshpakov commented on src/entities/Order.ts
> +  summa?: number;
Переименовал на amount

2021-11-22 17:02 UTC, dmshpakov commented on src/entities/Order.ts
>    person: DocumentReference<DocumentData>;
Нет, там будет ссылка на данные, по аналогии, dishRef из этого же типа

2021-11-22 17:02 UTC, dmshpakov commented on src/entities/Transaction.ts
> +  summa: number;
Переименовал на amount

2021-11-22 17:02 UTC, dmshpakov commented on src/pages/Home.tsx
> +          {currentUser && currentUser.role === 'admin' ? (
Поправил

2021-11-22 17:02 UTC, dmshpakov commented on src/pages/Home.tsx
> +            {todayOrders && todayOrders.length > 0 ? (
При таком формате нужно добавлять правило "Redundant double negation.(eslintno-extra-boolean-cast)". Оставил как есть.

2021-11-22 17:02 UTC, dmshpakov commented on src/pages/Home.tsx
> +              <span className={classes.pinInfo}>{calculatedPrice} руб.</span>
Да, почему бы и нет. Изменил на символ рубля.

2021-11-22 17:02 UTC, dmshpakov commented on src/store/transactions/transactions-actions.ts
> +    const refillResult = await collectionRefill
Переделал

2021-11-22 17:02 UTC, dmshpakov commented on src/router/AuthRoute.tsx
> +      await dispatch(fetchSettings());
Некоторые коллекции зависят друг от друга, для них оставил await. Независящие коллекции грузятся параллельно.

2021-11-22 17:02 UTC, dmshpakov commented on src/pages/OrdersDelivery/OrdersDeliveryWithoutDeposit.tsx
> +    // await dispatch(fetchUserInfo(currentUser.email!));
Да, удалил

2021-11-22 17:02 UTC, dmshpakov commented on src/pages/Profile/Profile.tsx
> +import './profile.scss';
Убрал доп. стили

2021-11-22 17:02 UTC, dmshpakov commented on src/pages/Profile/Profile.tsx
> +                {transactions.some((el) => el.type === 'refill') ? (
Сделал рефакторинг + удалил scss

2021-11-22 17:02 UTC, dmshpakov commented on src/pages/OrdersDelivery/OrdersDeliveryDeposit.tsx
> +  arr.forEach((el: UserNew) => {
Переделал

2021-11-22 17:02 UTC, dmshpakov commented on package.json
> +    "node-sass": "5.0.0",
Удалил

2021-11-23 08:53 UTC, Laconiez approved these changes

2021-11-23 08:53 UTC, merged